version: '3.9'

volumes:
  codeqa:
    external: true

services:
  init-codeqa:
    image: python:3.10
    volumes:
      - codeqa:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Installing gdown..."
        pip install --quiet gdown
        
        echo "Downloading codeqa.zip from Google Drive..."
        gdown --id 1vqeXmwJ2wKMD3xL2GAZJssOREot7k6mU -O codeqa.zip
        
        echo "Extracting codeqa.zip..."
        apt-get update && apt-get install -y unzip
        mkdir -p codeqa
        mv *.json codeqa/
        unzip -q codeqa.zip -d codeqa/ || true
        rm codeqa.zip
        
        echo "Dataset codeqa setup complete at /data/codeqa"
    restart: "no"