name: Chain Deployments

on:
  push:
    branches:
      - serving_stage_deploy

jobs:
  trigger-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Staging Deployment
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: Staging Deployment