name: Deploy Serving
on:
  push:
    branches:
      - serving
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  deploy_serving:
    runs-on: [self-hosted, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH keys
        run: |
          mkdir -p serving
          echo "${{ secrets.id_rsa }}" > serving/id_rsa
          echo "${{ secrets.id_rsa_pub }}" > serving/id_rsa.pub
          chmod 600 serving/id_rsa
          chmod 644 serving/id_rsa.pub

      - name: Setup OpenStack configuration
        run: |
          mkdir -p ~/.config/openstack
          echo "${{ secrets.CLOUDS_YAML_COMBINED }}" > ~/.config/openstack/clouds.yaml
          chmod 600 ~/.config/openstack/clouds.yaml
      
      - name: Setup CHI@UC app cred 
        run: |
          mkdir -p serving/scripts
          echo "${{ secrets.CHI_UC_OPENRC_SH }}" > serving/scripts/app-cred-uc-openrc.sh

      - name: Terraform Version
        working-directory: serving
        run: | 
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate leximind
          terraform version 
      
      - name: Terraform Init
        working-directory: serving
        run: terraform init

      - name: Terraform Validate
        working-directory: serving
        run: terraform validate

      - name: Terraform Plan
        working-directory: serving
        run: terraform plan -var-file ./use-cases/fastapi.tfvars | grep -E "Plan:|No changes|Error|#"

      - name: Terraform Apply
        working-directory: serving
        run: terraform apply -var-file ./use-cases/fastapi.tfvars -auto-approve