on:
  schedule:
    - cron: "0 4 * * 2,4,6" # Runs every Tuesday, Thursday, and Saturday at 12:00 AM EDT (4:00 AM UTC)

jobs:
  destroy-resources:
    runs-on: [self-hosted, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH keys
        run: |
          mkdir -p serving
          echo "${{ secrets.id_rsa }}" > serving/id_rsa
          echo "${{ secrets.id_rsa_pub }}" > serving/id_rsa.pub
          chmod 600 serving/id_rsa
          chmod 644 serving/id_rsa.pub

      - name: Setup OpenStack configuration
        run: |
          mkdir -p ~/.config/openstack
          echo "${{ secrets.clouds_yaml }}" > ~/.config/openstack/clouds.yaml
          chmod 600 ~/.config/openstack/clouds.yaml
          cat ~/.config/openstack/clouds.yaml

      - name: Terraform Version
        run: | 
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate leximind
          terraform version
      
      - name: Terraform Destroy Serving
        working-directory: serving
        run: | 
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate leximind
          terraform destroy -auto-approve
      
      - name: Terraform Destroy Monitoring
        working-directory: monitoring
        run: | 
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate leximind
          terraform destroy -auto-approve