name: Terraform Deploy

on:
  push:
    branches:
      - test-workflow

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH keys
        run: |
          mkdir -p serving
          echo "${{ secrets.id_rsa }}" > serving/id_rsa
          echo "${{ secrets.id_rsa_pub }}" > serving/id_rsa.pub
          chmod 600 serving/id_rsa
          chmod 644 serving/id_rsa.pub

      - name: Setup OpenStack configuration
        run: |
          mkdir -p ~/.config/openstack
          echo "${{ secrets.clouds_yaml }}" > ~/.config/openstack/clouds.yaml
          chmod 600 ~/.config/openstack/clouds.yaml
          cat ~/.config/openstack/clouds.yaml

      - name: Terraform Version
        working-directory: serving
        run: terraform version 

      # - name: Terraform Plan
      #   working-directory: serving
      #   run: terraform plan 

      # - name: Terraform Apply
      #   working-directory: serving
      #   run: terraform apply -auto-approve 